### PR TITLE
Add speech bubble tail

### PR DESCRIPTION
**Pull request by wjdqhry**
I wanted to convert the text into a speech bubble as well as an image. 
I added this setting for others.

```
const textToImage = require('text-to-image');

const text = "Hello world!"
const dataUri = await textToImage.generate(text, {
       debug: true,
       bubbleTail: {width: 20, height: 20},
       fontSize: 22,
       margin: 8,
       textAlign: "center",
       lineHeight: 1
});
```
image

### CODE REVIEW

**Comment by bostrom** [comment]
Thanks for the contribution @wjdqhry! Looks really good. Do you think you could write a test for the speech bubble tail too? Render it, then check that there's a white pixel where the tail should be.

**Comment by wjdqhry** [comment]
I put in the test code!
As shown in the picture, the alpha in the last two pixels wasn't 255, so I did -2.

image

**Comment by bostrom** [comment]
@wjdqhry I added your new option to the readme, rebased onto my master and forced pushed the changes to your branch. This made GitHub close the pull request and I'm not able to update your PR branch anymore. Can you please reopen or create a new PR from your fork?

**Comment by bostrom** [comment]
Never mind, I recreated the PR myself and merged. Thanks for your contribution! 🎉

**Comment by wjdqhry** [comment]
I'm sorry for replying late. Thank you.

**Pull request closed without merging**
