### PR TITLE
Colors validation solution.

### PR DESCRIPTION
**Pull request by iMrDJAi**
https://github.com/bostrom/text-to-image/issues/23

### CODE REVIEW

**Comment by bostrom** [comment]
Welcome back @iMrDJAi and thanks for the PR. 

Any reason why you prefer to have this validation built into this library when you could validate the color yourself before entering it as an input to text-to-image? 

It seems like an excellent library, but I'm reluctant to adding more dependencies, especially since I feel the use cases for needing to validate the color values are rather few. And also because it's so easy to do it in the calling software if really needed.

Thoughts?

**Comment by iMrDJAi** [comment]
> Any reason why you prefer to have this validation built into this library when you could validate the color yourself before entering it as an input to text-to-image?

@bostrom By looking at your code I find that if the user didn't provide a color at all, the library uses **default** as a fallback:
https://github.com/bostrom/text-to-image/blob/48aecc9dc5368fc9327f84622886d57e7f9ee31e/src/textToImage.ts#L250

It does make sense that the library takes care of the color **validation** for the user in addition of its **presence**, it's all about ease of use.  
In fact, at first I thought that the feature is already a thing, because the docs mention the default values of bgColor/textColor:

https://github.com/bostrom/text-to-image/blob/48aecc9dc5368fc9327f84622886d57e7f9ee31e/README.md#L50 https://github.com/bostrom/text-to-image/blob/48aecc9dc5368fc9327f84622886d57e7f9ee31e/README.md#L62

Do you see the problem here? the user will think by mistake that it actually fallbacks to default for any problem that may occur, that's exactly what happened with me.

**Comment by bostrom** [comment]
I fully understand your point. However, I never stated that the colors fall back to the default value **in case a bad value is given**. The interpretation of _default value_ is normally that the default value is used in case another value is **not given**. If the developer supplies a value for the colors, it's the developer's responsibility to make sure it's a proper value. 

My assumption is that in most cases the color values are set by the developer, in which cases a validation is unnecessary, since the developer should know what they're doing and any bad values will reveal themselves in testing. In your case, if I understand it correctly, the color values come from the users of your software? In my opinion, it's then your responsibility to validate your users' input, as any good UI would do.

To avoid the misunderstanding you faced, I'm very willing to more precisely state the meaning of the default values in the README, and also point to the library you suggested for checking the values. However, I'm still not convinced it's the responsibility of this library to validate user input. After all, it doesn't validate any other parameters either, so why validate only colors?

**Comment by iMrDJAi** [comment]
@bostrom I guess you're right, if the library validates one value it should validate the rest, and this probably should be done by the developer since he's the one who needs to decide what the output is.

You should definitely clearify that in the README, also you should mention that an invalid color produces transparent, and finally make an example on how to validate colors using validate-color library, this may help developers in such cases.

**Comment by bostrom** [comment]
Thanks @iMrDJAi for understanding! Good ideas for the Readme, I will add those as soon as possible! 

Don't hesitate to suggest more improvements in the future!

**Pull request closed without merging**
