### PR TITLE
feat: center text on custom height

### PR DESCRIPTION
**Pull request by OsirisFrik**
feature request: #69 - Center on custom height

## Options added:
* `centerHeight` as a boolean to don't affect previous versions implementations
* `fixHeightCenter` in case the margin affect calculation, this subtrac margin top

## Example:
```js
await txt2img.generate('Hello world', {
  customHeight: 100,
  textAlign: true,
  centerHeight: true
  margin: 5
```

⚠️ PLEASE ADD TYPES TO `index.d.ts` ⚠️

```ts
centerHeight?: boolean;
fixHeightCenter?: number;
```

I don't can add for any reason, on commit eslint return error `1:8  error  Parsing error: Unexpected token interface`, I search about it but don't found answer.

### Test helper

Added a tool for get index for frame data

### CODE REVIEW

**Comment by bostrom** [comment]
Nice job! 

Just a few remarks (see comments), and please add tests for the new options. 

I can check the eslint settings and possibly add the type definitions. It's not really set up to be a typescript project though...

**Review by bostrom — CHANGES_REQUESTED** [review]

**Comment by OsirisFrik** [comment]
hey @bostrom

can you help me with understend how you calculate te position?

```js
expect(centerAlignData.frames[0].data[400 * 19 * 4 + 13 * 4]).toEqual(0xff);
```

I suppose `400` it's the width and `19` it's the height, right? but what it's the anothers 3 numbers?

**Comment by bostrom** [comment]
Of course. It’s due to how that getImageData (or similar) function returns
the data. For each pixel there are four values (rgba most likely), so to
get the pixel at col 19, row 13, we have to multiply each row and col with
4). I should have made a helper for that, but haven’t yet.

**Comment by OsirisFrik** [comment]
@bostrom mmm... I don't know why in my local test return me 224, but her 255

**Comment by bostrom** [comment]
> @bostrom mmm... I don't know why in my local test return me 224, but her 255

@OsirisFrik you probably hit a pixel that is on the edge of the character, so it's a bit greyer than black. Try moving one pixel left/right/up/down to hit the middle of the character. 

You can also test this by checking that the top part of the image only contains white pixels. So if the image is 100px high, and your text is ~14px high, the top 70px, at least, shouldn't contain anything else than white pixels. So you could sum up all image data values (rgb for all pixels) for that area and expect it to be (255 * 3 * number of pixels). 

And likewise for the middle part: you could check that it **doesn't** contain only white pixels, by summing them up and expect the sum to be less than (255 * 3 * number of pixels). 

What do you think?

**Comment by OsirisFrik** [comment]
finally!!

I use your center text test because can't be same

**Comment by bostrom** [comment]
@OsirisFrik Thanks! I modified your test to check the different parts of the image as I outlined before. 

But then I started looking more closely at the implementation and found a few issues, partly related to other things than this. So I'll spend some time reworking the `verticalAlign` and `customHeight` configurations and some other things as well during this week.

**Pull request merged**
